# Generated by Django 5.1.2 on 2024-11-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='image',
        ),
    ]
